add maven_01 task
wilden5/OnlineStoreAQA pull request #1
Opened 2021-06-01 20:30 UTC by wilden5

added the first task

2021-06-02 09:32 UTC, artemmoroz requested changes
Please
1. correct naming, according to maven guides (artifactid and so on)
2. create a proper gitignore, https://www.toptal.com/developers/gitignore
3. correct modules structure

2021-06-02 09:32 UTC, artemmoroz commented on pom.xml
> +        <module>parent</module>
parent is not a module, it is parent (in your case this pom should be a parent)

2021-06-02 09:32 UTC, artemmoroz commented on pom.xml
> +    <groupId>JavaAQA</groupId>
naming conventions

2021-06-02 21:22 UTC, wilden5 commented
> Please
> 
> 1. correct naming, according to maven guides (artifactid and so on)
> 2. create a proper gitignore, https://www.toptal.com/developers/gitignore
> 3. correct modules structure

Hello, I changed the project structure and maven naming in the project. Also, edited gitignore file.

2021-06-04 08:52 UTC, artemmoroz requested changes
according prev comments everything is fine, but you ve already commited files that should be ignored *idea, *iml and so on, you should remove them https://stackoverflow.com/questions/19663093/apply-gitignore-on-an-existing-repository-already-tracking-large-number-of-file

2021-06-04 23:19 UTC, wilden5 commented
> according prev comments everything is fine, but you ve already commited files that should be ignored *idea, *iml and so on, you should remove them https://stackoverflow.com/questions/19663093/apply-gitignore-on-an-existing-repository-already-tracking-large-number-of-file

Removed unnecessary files from the project. Thanks for helping me find the right git console commands!

2021-06-08 09:08 UTC, artemmoroz approved these changes

2021-06-08 09:08 UTC, merged