add store functionality and reflection
wilden5/OnlineStoreAQA pull request #2
Opened 2021-06-12 11:50 UTC by wilden5

Hello, main store functionality and reflection was added

2021-06-14 10:22 UTC, artemmoroz requested changes

2021-06-14 10:22 UTC, artemmoroz commented on domain/src/main/java/com/denis/domain/Category.java
> +    public String name;
i think this field should be private or protected

2021-06-14 10:22 UTC, artemmoroz commented on domain/src/main/java/com/denis/domain/Category.java
> +    private List<Product> productList;
this seems to be protected

2021-06-14 10:22 UTC, artemmoroz commented on store/src/main/java/com/denis/store/Store.java
> +        List<String> printStore = new ArrayList<>();
it is better to you StringBuffer or StringBuilder for that.

2021-06-15 17:40 UTC, wilden5 commented
Hello, I've changed all issues that you described above

2021-06-18 11:04 UTC, artemmoroz approved these changes

2021-06-18 11:04 UTC, merged