add collections_04 task
wilden5/OnlineStoreAQA pull request #3
Opened 2021-07-10 12:47 UTC by wilden5

add store commands

2021-07-13 12:07 UTC, artemmoroz requested changes
solid, flexible functions

2021-07-13 12:07 UTC, artemmoroz commented on consoleApp/src/main/java/com/denis/consoleapp/StoreApp.java
> +                executeStore(scanner, store);
* try to remove it from here

2021-07-13 12:07 UTC, artemmoroz commented on store/src/main/java/com/denis/store/Store.java
> +    public void printSort() {
SOLID, move somewhere

2021-07-13 12:07 UTC, artemmoroz commented on store/src/main/java/com/denis/store/Store.java
> +    public void printSort() {
for al print methods

2021-07-13 12:07 UTC, artemmoroz commented on store/src/main/java/com/denis/store/Store.java
> +        List<Category> cloneCategory = new ArrayList<>();
line 41-55 -> Clonable inteface (deep clone)

2021-07-13 12:07 UTC, artemmoroz commented on store/src/main/java/com/denis/store/Store.java
> +        int indexCut = (allProducts.size() > 5) ? 5 : allProducts.size();
list.stream.limit

2021-07-13 12:07 UTC, artemmoroz commented on store/src/main/java/com/denis/store/utility/CommandSortComparator.java
> +    List<XmlReader.SortRules> sortRules;
single class (map)

2021-07-13 12:07 UTC, artemmoroz commented on store/src/main/java/com/denis/store/utility/XmlReader.java
> +        InputStream istream = XmlReader.class.getResourceAsStream("SortParams.xml");
filename - move to func params

2021-07-19 19:34 UTC, wilden5 commented
solved the noted issues

2021-07-21 16:30 UTC, artemmoroz commented on store/src/main/java/com/denis/store/utility/CommandSortComparator.java
> +    List<XmlReader.SortRules> sortRules;
what about that comment? as i remember, we decided to make generic comparator, that will use some generic settings for comparing, like map<string, string> and not bound to xml reader or so.

2021-08-02 09:14 UTC, artemmoroz approved these changes

2021-08-02 09:15 UTC, merged