add patterns_05 task
wilden5/OnlineStoreAQA pull request #4
Opened 2021-08-08 19:42 UTC by wilden5

Applied Singleton and Command patterns to project

2021-08-11 19:29 UTC, wilden5 commented
I am added **multithreading_06** task to this PR and refactored patterns

2021-08-16 10:58 UTC, artemmoroz requested changes
in the future, you'd better use different jumps for different tasks

2021-08-16 10:58 UTC, artemmoroz commented on consoleApp/src/main/java/com/denis/consoleapp/service/PrintOrderCommand.java
> +    public void execute() {
please think about refactoring of these method(class), cause now it looks like mess. some improvements: 1. move schedulers to separate method/class, 2. take a look at performance, cause you read data N times in cycles, you can optimize it, 3. printiing

2021-08-16 10:58 UTC, artemmoroz commented on consoleApp/src/main/java/com/denis/consoleapp/service/PrintTopPriceCommand.java
> +        ArrayList<Product> allProducts = new ArrayList<>();
List... = new ArrayList

2021-08-16 10:58 UTC, artemmoroz commented on consoleApp/src/main/java/com/denis/consoleapp/service/PrintTopPriceCommand.java
> +        HashMap sortParams = new HashMap<>();
Map ....

2021-08-16 10:58 UTC, artemmoroz commented on consoleApp/src/main/java/com/denis/consoleapp/service/Switch.java
> +public class Switch {
i did not get the idea of this class, if you want to organize commands - it is not the best solution. please make a deeper look on command pattern or chain of responsibility pattern

2021-08-16 10:58 UTC, artemmoroz commented on store/src/main/java/com/denis/store/Store.java
> +    public static Store getInstance() {
what for it is singleton? if just to apply this pattern - it is not the best choice, if not - please comment

2021-08-23 14:10 UTC, artemmoroz requested changes
phone call

2021-08-27 13:33 UTC, artemmoroz requested changes

2021-08-27 13:33 UTC, artemmoroz commented on store/src/main/java/com/denis/store/utility/BaseString.java
> +public class BaseString {
very strange class name, may be PrintService, or PrintHelper would be better

2021-08-27 13:33 UTC, artemmoroz commented on store/src/main/java/com/denis/store/utility/BaseString.java
> +    public String printCategories(List<Category> categoryList) {
these methods (this and above) are utilities methods, and could be static, it that case you shhould not create BaseString instance and provide it to other methods.

2021-08-27 20:38 UTC, wilden5 commented
Fixed the last issues

2021-08-30 10:11 UTC, artemmoroz approved these changes

2021-08-30 10:12 UTC, merged